export interface Template {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const TEMPLATES: Template[] = [
  {
    id: 'blank',
    name: 'Blank Page',
    description: 'Clean page with margins',
    icon: 'file',
  },
  {
    id: 'thoroughly-blank',
    name: 'Thoroughly Blank',
    description: 'No margins, edge to edge',
    icon: 'square',
  },
  {
    id: 'working-sheet',
    name: 'Working Sheet',
    description: 'Subtle grid for drafting',
    icon: 'layout-grid',
  },
  {
    id: 'school-copy',
    name: 'School Copy',
    description: 'Wide ruled with margin',
    icon: 'book-open',
  },
  {
    id: 'lined',
    name: 'Lined Paper',
    description: 'Standard ruled lines',
    icon: 'align-left',
  },
  {
    id: 'graph',
    name: 'Graph Paper',
    description: 'Square grid pattern',
    icon: 'grid-3x3',
  },
  {
    id: 'dot-grid',
    name: 'Dot Grid',
    description: 'Dotted grid pattern',
    icon: 'grip',
  },
  {
    id: 'music-sheet',
    name: 'Music Sheet',
    description: 'Staff lines for music',
    icon: 'music',
  },
  {
    id: 'engineering',
    name: 'Engineering Paper',
    description: 'Fine grid with margins',
    icon: 'ruler',
  },
  {
    id: 'cornell-notes',
    name: 'Cornell Notes',
    description: 'Study note-taking format',
    icon: 'notebook',
  },
  {
    id: 'planner',
    name: 'Daily Planner',
    description: 'Schedule with time slots',
    icon: 'calendar',
  },
  {
    id: 'calligraphy',
    name: 'Calligraphy',
    description: 'Guidelines for lettering',
    icon: 'pen-tool',
  },
  {
    id: 'isometric',
    name: 'Isometric Grid',
    description: '3D drawing grid',
    icon: 'box',
  },
  {
    id: 'hexagon',
    name: 'Hexagon Grid',
    description: 'Hex pattern for gaming',
    icon: 'hexagon',
  },
  {
    id: 'storyboard',
    name: 'Storyboard',
    description: 'Frames for visual planning',
    icon: 'film',
  },
];

export interface TemplateConfig {
  lineSpacing: number; // mm
  marginTop: number; // mm
  marginBottom: number; // mm
  marginLeft: number; // mm
  marginRight: number; // mm
  showMarginLine: boolean;
  gridSize: number; // mm (for graph paper)
  lineColor: string;
  marginLineColor: string;
  pageColor: string;
}

export const DEFAULT_CONFIGS: Record<string, TemplateConfig> = {
  'blank': {
    lineSpacing: 0,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#d1d5db',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'thoroughly-blank': {
    lineSpacing: 0,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#d1d5db',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'working-sheet': {
    lineSpacing: 0,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 15,
    marginRight: 15,
    showMarginLine: false,
    gridSize: 5,
    lineColor: '#e5e7eb',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'school-copy': {
    lineSpacing: 8,
    marginTop: 25,
    marginBottom: 20,
    marginLeft: 30,
    marginRight: 15,
    showMarginLine: true,
    gridSize: 0,
    lineColor: '#93c5fd',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'lined': {
    lineSpacing: 7,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#d1d5db',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'graph': {
    lineSpacing: 0,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    showMarginLine: false,
    gridSize: 5,
    lineColor: '#c7d2fe',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'dot-grid': {
    lineSpacing: 0,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    showMarginLine: false,
    gridSize: 5,
    lineColor: '#9ca3af',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'music-sheet': {
    lineSpacing: 2,
    marginTop: 25,
    marginBottom: 25,
    marginLeft: 20,
    marginRight: 20,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#1f2937',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'engineering': {
    lineSpacing: 0,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 25,
    marginRight: 10,
    showMarginLine: true,
    gridSize: 2,
    lineColor: '#86efac',
    marginLineColor: '#22c55e',
    pageColor: '#f0fdf4',
  },
  'cornell-notes': {
    lineSpacing: 7,
    marginTop: 50,
    marginBottom: 60,
    marginLeft: 60,
    marginRight: 15,
    showMarginLine: true,
    gridSize: 0,
    lineColor: '#d1d5db',
    marginLineColor: '#3b82f6',
    pageColor: '#ffffff',
  },
  'planner': {
    lineSpacing: 12,
    marginTop: 30,
    marginBottom: 20,
    marginLeft: 50,
    marginRight: 15,
    showMarginLine: true,
    gridSize: 0,
    lineColor: '#e5e7eb',
    marginLineColor: '#6366f1',
    pageColor: '#ffffff',
  },
  'calligraphy': {
    lineSpacing: 10,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#93c5fd',
    marginLineColor: '#ef4444',
    pageColor: '#fffbeb',
  },
  'isometric': {
    lineSpacing: 0,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    showMarginLine: false,
    gridSize: 10,
    lineColor: '#c7d2fe',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'hexagon': {
    lineSpacing: 0,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    showMarginLine: false,
    gridSize: 8,
    lineColor: '#a5b4fc',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
  'storyboard': {
    lineSpacing: 0,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    showMarginLine: false,
    gridSize: 0,
    lineColor: '#374151',
    marginLineColor: '#ef4444',
    pageColor: '#ffffff',
  },
};
